version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 1
    commit-message:
      prefix: "chore"
      include: "scope"
