name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v4
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: Cache ESLint dependencies
      uses: actions/cache@v4
      with: 
        path: ./packages/client/.cache/eslint
        key: ${{ runner.os }}-eslint-${{ hashFiles('yarn.lock') }}-${{ hashFiles('**/.eslintrc.cjs') }}
        restore-keys: |
          ${{ runner.os }}-eslint-

    - name: Cache Playwright browsers
      id: cache-playwright
      uses: actions/cache@v4
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-playwright-

    - name: Restore Docker image cache
      uses: actions/cache@v4
      with:
        path: /tmp/docker-cache
        key: docker-images-${{ runner.os }}
        restore-keys: |
          docker-images-
    
    - name: Load cached Docker images
      run: |
        if [ -d /tmp/docker-cache ]; then
          for img in /tmp/docker-cache/*.tar; do
            docker load -i "$img"
          done
        fi

    - name: Install dependencies
      if: steps.cache-node-modules.outputs.cache-hit != 'true'
      run: yarn install --frozen-lockfile

    - name: Install Playwright browsers
      if: steps.cache-playwright.outputs.cache-hit != 'true'
      run: yarn ws client playwright:install

    - name: Bootstrap
      run: yarn bootstrap:ci

    - name: Lint
      run: yarn lint:ci

    - name: Test
      run: yarn test

    - name: Build
      run: yarn build

    - name: Deploy
      run: yarn deploy

    - name: Publish
      uses: cloudflare/pages-action@v1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: soulglow
        directory: packages/client/dist
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}


